### ISSUE TITLE
Timeline Checklist

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#134]
Before Dec 24th
- [x]  Karin will get all wireframes up and issues sorted (with extra explanation/commentary if needed)  (hoping this will be done this week still but we will see how it goes!)
- [x]  Karin will email Lorna when done with wireframes
- [x]  Lorna will resend Karin images email
 
Before Jan 11th: 
- [x]  Lorna will go through all wireframes and sign off on changes/wording (will all be linked from https://github.com/CDRH/african_poetics/issues/130 by Dec 24th)
- [x]  Programmers will have process set up for pushing changes (https://github.com/CDRH/african_poetics/issues/127)
 
Before Jan 18th: 
- [x]  Karin/Programmers will make changes from wireframes/work on any other issues
 
Week of Jan 18, finished by Jan 22nd: 
- [x]  Lorna and Karin will work through final design issues together
 
Week of Jan 25th (some may happen week before)
- [x]  Programmers will push final changes to live site
- [x]  Remove passwords
- [x]  Run link check
- [x]  Finalize docs for posting instructions/info about when push to live site will happen
