### ISSUE TITLE
Master todo list for airtable to ES transformation

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#208]
- [ ] create spreadsheet to track progress
- [ ] create initial scripts to pull down data as CSV
- [ ] on news items tab, work out what field names will be needed 
- [ ] on events tab, work out what field names will be needed
- [ ] on people tab, work out what field names will be needed
- [ ] on works tab, work out what field names will be needed
- [ ] create new fields for news items in airtable, as noted in spreadsheet
- [ ] create new fields for events in airtable, as noted in spreadsheet
- [ ] create new fields for people in airtable, as noted in spreadsheet
- [ ] create new fields for works, as noted in spreadsheet
- [ ] news items: alter scripts to pull down data to include all fields indicated in spreadsheet and added to airtable
- [ ] events: alter scripts to pull down data to include all fields indicated in spreadsheet and added to airtable
- [ ] people: alter scripts to pull down data to include all fields indicated in spreadsheet and added to airtable
- [ ] works: alter scripts to pull down data to include all fields indicated in spreadsheet and added to airtable
- [ ] news items: add data to api from pulled CSVs, following field names on spreadsheet
- [ ] events: add data to api from pulled CSVs, following field names on spreadsheet
- [ ] people: add data to api from pulled CSVs, following field names on spreadsheet
- [ ] works: add data to api from pulled CSVs, following field names on spreadsheet
- [ ] annotate screenshot of news item front end with field names
- [ ] annotate screenshot of events front end with field names
- [ ] annotate screenshot of people front end with field names
- [ ] annotate screenshot of works front end with field names
- [ ] news items: alter rails view to pull new data from api, based on screenshot annotations
- [ ] events: alter rails view to pull new data from api, based on screenshot annotations
- [ ] people: alter rails view to pull new data from api, based on screenshot annotations
- [ ] works: alter rails view to pull new data from api, based on screenshot annotations
- [ ] document process to pull new data and post to index
    

Reference: 

API fields: https://docs.google.com/spreadsheets/d/1Qo-TF6l3mHZ0n8piP6E76dMU6FkVEucPh42HmvhJ6jc/edit#gid=1285211623
