### ISSUE TITLE
Notes from Sep 30th meeting re:  October 14th Launch

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#3]
Split into another issue as needed, these are notes from 9/30/2019 meeting

- [x] map should be changed to a "region" map for now, we will go back to countries later https://github.com/CDRH/african_poetics/issues/4
- launch date at africanpoetics.unl.edu near october 14
- they will get info to karin by october 9
- [x] main sections/pages/browse:  https://github.com/CDRH/african_poetics/issues/5
    - Home (this is the "CAP" home, not the african poetics home, might need to think about it?
    - Browse
    - Search (?)
    - About
    - Featured
- and the 4 on the home page: 
    - Browse by Poet
    - Browse by Featured Poet
    - Browse by Region
    - Browse by Works
- [x] Need to get more text indexed into the poets (all fields) https://github.com/CDRH/african_poetics/issues/6
- [x] Remove "Source"https://github.com/CDRH/african_poetics/issues/7
- [x] Will create HTML pages for 5 featured poets, need to figure out how to show html only on their pages https://github.com/CDRH/african_poetics/issues/8
