### ISSUE TITLE
Omeka S ingest issues

### ISSUE THREAD

**Issue by wkdewey** [CDRH/african_poetics#386]
**Bugs that still need to be fixed, missing functionality**

- [ ] Make sure that duplicates linked don't appear when posting again (I tried to fix this but it is still happening)
- [ ] Fix items ids that aren't being linked due to being missing in the database, or having mangled Markdown. I think the problem is on the Airtable side
- [ ] handling dates with the module
- [ ] Make sure that blank items are properly handled (see suggestions on Wren's spreadsheets)
- [ ] Make sure everything is being linked up and that some aren't missing
- [ ] check for arrays that need to be parsed as JSON, fields with airtable IDs that need to be removed
- [ ] Items (instead of item sets, as intended) are wrongly being marked as being "Collections"

**Todos for linking with new site**

- [ ] Make a branch with smaller versions of spreadsheets, like 10 items at a time
- [ ] ingest each sheet
- - [ ] People
- - [ ] News items
- - [ ] Events
- - [ ] Works
- - [ ] Commentaries
- - [ ] Link items together
- [ ] Make sure fields match what front end is expecting
- [ ] Add item sets where needed

**Posting functionality wishlist**

- [ ] add option to post individual sheets
- [ ] add option to delete items from command line
- [ ] improve code performance
